from django.utils.translation import get_language
from .models import SEOMeta

def translations(request):
    lang = get_language()
    
    data = {
        'uz': {
            'site_title': 'ElectroPro - Professional Elektr Xizmatlari',
            'tashkent_city': 'Toshkent shahri',
            'services': 'Xizmatlar',
            'about_us': 'Biz haqimizda',
            'track_order': 'Arizani kuzatish',
            'login': 'Kirish',
            'leave_request': 'Ariza qoldirish',
            'cabinet': 'Kabinet',
            'hero_title_1': 'Toshkentda Professional',
            'hero_title_2': 'Elektriklar',
            'hero_desc': 'Uyingiz yoki ofisingiz uchun ishonchli va malakali ustalarni chaqiring. Barcha ishlarga kafolat beramiz.',
            'order_now': 'Hoziroq buyurtma bering',
            'exp_masters': 'Tajribali ustalar',
            'done_orders': 'Bajarilgan ishlar',
            'client_name': 'Ismingiz',
            'phone_number': 'Telefon raqam',
            'additional_phone': 'Qo\'shimcha telefon raqami (ixtiyoriy)',
            'what_needs_done': 'Nima ish qilinishi kerak?',
            'your_region': 'Hududingiz (Viloyat)',
            'district': 'Tuman / Shahar',
            'exact_address': 'Aniq manzil (Mahalla, ko\'cha, uy raqami)',
            'placeholder_address': 'Masalan: Yangiobod MFY, Buyuk Ipak Yo\'li ko\'chasi, 24-uy, 15-xonadon',
            'urgency': 'Shoshilinchlik darajasi',
            'urgency_low': 'Oddiy (muammo shoshilinch emas)',
            'urgency_medium': 'Muhim (tezroq hal qilinishi kerak)',
            'urgency_high': 'Favqulodda (shoshilinch yordam!) 🚨',
            'send_req': 'Arizani yuborish',
            'yandex_map_url_label': 'Yandex Xarita havolasi yoki koordinatalari (ixtiyoriy)',
            'yandex_map_hint': 'Yandex Maps ilovasidan ulashish (Share) havolasini nusxalab joylashtirsangiz, usta sizni oson topadi.',
            'placeholder_yandex': 'Masalan: https://yandex.uz/maps/... yoki 41.311081, 69.240562',
            'placeholder_name': 'Ismingizni kiriting',
            'placeholder_problem': 'Muammoni qisqacha yozing...',
            'electrical_services': 'Elektr xizmatlari',
            'all_services': 'Barcha xizmatlar',
            'coverage_areas': 'Xizmat ko\'rsatish hududlari',
            'coverage_desc': 'Biz O\'zbekistonning barcha viloyatlarida professional xizmat ko\'rsatamiz.',
            'our_specialists': 'Bizning Mutaxassislarimiz',
            'specialists_desc': 'ElectroPro faqat sinalgan, malakali va maxsus ruxsatnomaga ega bo\'lgan ustalar bilan ishlaydi.',
            'experience': 'Tajriba',
            'call_master': 'Chaqirish',
            'calc_title': 'Xizmatlar Kalkulyatori',
            'calc_desc': 'Taxminiy xizmat haqini hisoblang',
            'total_sum': 'Jami summa',
            'som': 'so\'m',
            'years': 'yil',
            'footer_desc': 'O\'zbekiston bo\'ylab professional elektr montaj va innovatsion yechimlar provayderi.',
            'company': 'Kompaniya',
            'help': 'Yordam',
            'vacancies': 'Vakansiyalar',
            'news': 'Yangiliklar',
            'calculator': 'Kalkulyator',
            'all_rights': 'Barcha huquqlar himoyalangan',
            'faq': 'FAQ',
            'contact': 'Bog\'lanish',
            'services_intro': 'Biz O\'zbekiston bo\'ylab professional elektr xizmatlarini taqdim etamiz.',
            'install_works': 'Elektr Montaj',
            'ev_charging': 'EV Zaryadka Stansiyasi',
            'high_voltage': 'Yuqori kuchlanish ishlari',
            'about_intro': 'ElectroPro — O\'zbekistondagi eng ishonchli elektr xizmat provayderi.',
            'our_mission': 'Bizning Missiyamiz',
            'our_values': 'Bizning Qadriyatlarimiz',
            'safety': 'Xavfsizlik',
            'speed': 'Tezkorlik',
            'warranty': 'Kafolat',
            'address': 'Manzil',
            'work_hours': 'Ish vaqti',
            'extra_info': 'Qo\'shimcha ma\'lumotlar',
            'transport': 'Jamoat transporti',
            'social_media': 'Ijtimoiy tarmoqlar',
            'geolokatsiya': 'Geolokatsiya',
            'invoice_est': 'Hisob-faktura (Taxminiy)',
            'select_services': 'Xizmatlarni tanlang',
            'nothing_selected': 'Hali hech narsa tanlanmadi',
            'regions': {
                'tashkent_city': 'Toshkent shahri',
                'tashkent_v': 'Toshkent viloyati',
                'andijan': 'Andijon viloyati',
                'bukhara': 'Buxoro viloyati',
                'fergana': 'Farg\'ona viloyati',
                'jizzakh': 'Jizzax viloyati',
                'khorezm': 'Xorazm viloyati',
                'namangan': 'Namangan viloyati',
                'navoiy': 'Navoiy viloyati',
                'qashqadaryo': 'Qashqadaryo viloyati',
                'karakalpakstan': 'Qoraqalpog\'iston',
                'samarkand': 'Samarqand viloyati',
                'sirdaryo': 'Sirdaryo viloyati',
                'surxondaryo': 'Surxondaryo viloyati',
            }
        },
        'ru': {
            'site_title': 'ElectroPro - Профессиональные Электроуслуги',
            'tashkent_city': 'г. Ташкент',
            'services': 'Услуги',
            'about_us': 'О нас',
            'track_order': 'Отследить заявку',
            'login': 'Вход',
            'leave_request': 'Оставить заявку',
            'cabinet': 'Кабинет',
            'hero_title_1': 'Профессиональные',
            'hero_title_2': 'Электрики в Ташкенте',
            'hero_desc': 'Вызовите надежных и квалифицированных мастеров для дома или офиса. Даем гарантию на все работы.',
            'order_now': 'Заказать сейчас',
            'exp_masters': 'Опытных мастеров',
            'done_orders': 'Выполненных работ',
            'client_name': 'Ваше имя',
            'phone_number': 'Номер телефона',
            'additional_phone': 'Дополнительный телефон (опционально)',
            'what_needs_done': 'Что нужно сделать?',
            'your_region': 'Ваш регион (Область)',
            'district': 'Район / Город',
            'exact_address': 'Точный адрес (Махалля, улица, номер дома)',
            'placeholder_address': 'Например: махалля Янгиобод, ул. Буюк Ипак Йули, д. 24, кв. 15',
            'urgency': 'Уровень срочности',
            'urgency_low': 'Обычный (несрочно)',
            'urgency_medium': 'Важный (требуется быстрее)',
            'urgency_high': 'Экстренно (срочная помощь!) 🚨',
            'send_req': 'Отправить заявку',
            'yandex_map_url_label': 'Ссылка на Яндекс Карту или координаты (опционально)',
            'yandex_map_hint': 'Вы можете скопировать ссылку «Поделиться» из Яндекс Карт и вставить её сюда, чтобы мастер быстро вас нашёл.',
            'placeholder_yandex': 'Например: https://yandex.uz/maps/... или 41.311081, 69.240562',
            'placeholder_name': 'Введите ваше имя',
            'placeholder_problem': 'Кратко опишите проблему...',
            'electrical_services': 'Электроуслуги',
            'all_services': 'Все услуги',
            'coverage_areas': 'Территории обслуживания',
            'coverage_desc': 'Мы оказываем профессиональные услуги во всех регионах Узбекистана.',
            'our_specialists': 'Наши Специалисты',
            'specialists_desc': 'ElectroPro работает только с проверенными, квалифицированными мастерами с допусками.',
            'experience': 'Опыт',
            'call_master': 'Вызвать',
            'calc_title': 'Калькулятор Услуг',
            'calc_desc': 'Рассчитайте примерную стоимость работ',
            'total_sum': 'Итоговая сумма',
            'som': 'сум',
            'years': 'лет',
            'footer_desc': 'Провайдер профессионального электромонтажа и инновационных решений по всему Узбекистану.',
            'company': 'Компания',
            'help': 'Помощь',
            'vacancies': 'Вакансии',
            'news': 'Новости',
            'calculator': 'Калькулятор',
            'all_rights': 'Все права защищены',
            'faq': 'Чаво',
            'contact': 'Контакты',
            'services_intro': 'Мы предоставляем профессиональные электроуслуги по всему Узбекистану.',
            'install_works': 'Электромонтаж',
            'ev_charging': 'Зарядные станции для ЭМ',
            'high_voltage': 'Высоковольтные работы',
            'about_intro': 'ElectroPro — самый надежный поставщик электроуслуг в Узбекистане.',
            'our_mission': 'Наша Миссия',
            'our_values': 'Наши Ценности',
            'safety': 'Безопасность',
            'speed': 'Оперативность',
            'warranty': 'Гарантия',
            'address': 'Адрес',
            'work_hours': 'Рабочее время',
            'extra_info': 'Дополнительная информация',
            'transport': 'Общественный транспорт',
            'social_media': 'Социальные сети',
            'geolokatsiya': 'Геолокация',
            'invoice_est': 'Счет-фактура (Примерный)',
            'select_services': 'Выберите услуги',
            'nothing_selected': 'Ничего не выбрано',
            'regions': {
                'tashkent_city': 'г. Ташкент',
                'tashkent_v': 'Ташкентская обл.',
                'andijan': 'Андижанская обл.',
                'bukhara': 'Бухарская обл.',
                'fergana': 'Ферганская обл.',
                'jizzakh': 'Джизакская обл.',
                'khorezm': 'Хорезмская обл.',
                'namangan': 'Наманганская обл.',
                'navoiy': 'Навоийская обл.',
                'qashqadaryo': 'Кашкадарьинская обл.',
                'karakalpakstan': 'Каракалпакстан',
                'samarkand': 'Самаркандская обл.',
                'sirdaryo': 'Сырдарьинская обл.',
                'surxondaryo': 'Сурхандарьинская обл.',
            }
        },
        'en': {
            'site_title': 'ElectroPro - Professional Electrical Services',
            'tashkent_city': 'Tashkent City',
            'services': 'Services',
            'about_us': 'About Us',
            'track_order': 'Track Order',
            'login': 'Login',
            'leave_request': 'Leave Request',
            'cabinet': 'Cabinet',
            'hero_title_1': 'Professional',
            'hero_title_2': 'Electricians in Tashkent',
            'hero_desc': 'Call reliable and qualified masters for your home or office. We guarantee all work.',
            'order_now': 'Order Now',
            'exp_masters': 'Experienced Masters',
            'done_orders': 'Completed Orders',
            'client_name': 'Your Name',
            'phone_number': 'Phone Number',
            'additional_phone': 'Secondary Phone (optional)',
            'what_needs_done': 'What needs to be done?',
            'your_region': 'Your Region (Province)',
            'district': 'District / City',
            'exact_address': 'Exact Address (Mahalla, street, house/apt number)',
            'placeholder_address': 'e.g. Yangiobod mahalla, Buyuk Ipak Yoli street, house 24, apt 15',
            'urgency': 'Urgency level',
            'urgency_low': 'Normal (not urgent)',
            'urgency_medium': 'Important (needs fast action)',
            'urgency_high': 'Emergency (urgent help!) 🚨',
            'send_req': 'Send Request',
            'yandex_map_url_label': 'Yandex Maps link or coordinates (optional)',
            'yandex_map_hint': 'You can copy and paste a Share link from Yandex Maps here so the master can find you easily.',
            'placeholder_yandex': 'e.g. https://yandex.com/maps/... or 41.311081, 69.240562',
            'placeholder_name': 'Enter your name',
            'placeholder_problem': 'Briefly describe the problem...',
            'electrical_services': 'Electrical Services',
            'all_services': 'All Services',
            'coverage_areas': 'Coverage Areas',
            'coverage_desc': 'We provide professional services in all regions of Uzbekistan.',
            'our_specialists': 'Our Specialists',
            'specialists_desc': 'ElectroPro works only with proven, qualified masters with special permits.',
            'experience': 'Experience',
            'call_master': 'Call',
            'calc_title': 'Service Calculator',
            'calc_desc': 'Calculate the approximate cost of services',
            'total_sum': 'Total sum',
            'som': 'sum',
            'years': 'years',
            'footer_desc': 'Provider of professional electrical installation and innovative solutions throughout Uzbekistan.',
            'company': 'Company',
            'help': 'Help',
            'vacancies': 'Vacancies',
            'news': 'News',
            'calculator': 'Calculator',
            'all_rights': 'All rights reserved',
            'faq': 'FAQ',
            'contact': 'Contact',
            'services_intro': 'We provide professional electrical services throughout Uzbekistan.',
            'install_works': 'Electrical Installation',
            'ev_charging': 'EV Charging Stations',
            'high_voltage': 'High Voltage Works',
            'about_intro': 'ElectroPro — the most reliable electrical service provider in Uzbekistan.',
            'our_mission': 'Our Mission',
            'our_values': 'Our Values',
            'safety': 'Safety',
            'speed': 'Speed',
            'warranty': 'Warranty',
            'address': 'Address',
            'work_hours': 'Working Hours',
            'extra_info': 'Extra Information',
            'transport': 'Public Transport',
            'social_media': 'Social Media',
            'geolokatsiya': 'Geolocation',
            'invoice_est': 'Invoice (Estimated)',
            'select_services': 'Select services',
            'nothing_selected': 'Nothing selected yet',
            'regions': {
                'tashkent_city': 'Tashkent City',
                'tashkent_v': 'Tashkent Region',
                'andijan': 'Andijan Region',
                'bukhara': 'Bukhara Region',
                'fergana': 'Fergana Region',
                'jizzakh': 'Jizzakh Region',
                'khorezm': 'Khorezm Region',
                'namangan': 'Namangan Region',
                'navoiy': 'Navoiy Region',
                'qashqadaryo': 'Qashqadaryo Region',
                'karakalpakstan': 'Karakalpakstan',
                'samarkand': 'Samarkand Region',
                'sirdaryo': 'Sirdaryo Region',
                'surxondaryo': 'Surxondaryo Region',
            }
        }
    }
    
    return {'txt': data.get(lang, data['uz'])}

def seo_meta(request):
    path = request.path
    meta = SEOMeta.objects.filter(page_url=path).first()
    if meta:
        return {
            'seo': {
                'title': meta.translated_title,
                'description': meta.translated_description,
                'keywords': meta.translated_keywords
            }
        }
    else:
        # Default fallback
        return {
            'seo': {
                'title': 'ElectroPro - Professional Elektr Xizmatlari',
                'description': 'Toshkentda va O\'zbekiston bo\'ylab professional elektrik xizmatlari. Uyingiz va ofisingiz uchun ishonchli ustalar.',
                'keywords': 'elektrik, usta, toshkent, elektr montaj, rozetka o\'rnatish'
            }
        }
