# Generated by Django 6.0.5 on 2026-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Xizmat nomi (masalan: EV Zaryadka)')),
                ('material_list', models.TextField(verbose_name="Kerakli materiallar ro'yxati")),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Rasm')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiyasi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat')),
                ('user_identity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shaxs turi')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat turi')),
                ('message', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Murojaat vaqti')),
                ('is_processed', models.BooleanField(default=False, verbose_name="Ko'rib chiqildi")),
            ],
            options={
                'verbose_name': 'Murojaat ',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_staff', models.IntegerField(default=0, verbose_name='Jami ishchilar soni')),
                ('available_staff', models.IntegerField(default=0, verbose_name='Hozir bor ishchilar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xodimlar holati',
                'verbose_name_plural': 'Xodimlar holati',
            },
        ),
    ]
