# Generated by Django 6.0.5 on 2026-05-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qachon qulay?'),
        ),
    ]
