# Generated by Django 6.0.5 on 2026-05-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicerequest_preferred_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('ACCEPTED', 'Qabul qilindi'), ('COMPLETED', 'Bajarildi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
