# Generated by Django 6.0.5 on 2026-05-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_servicerequest_assigned_to_servicerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Rasmi')),
                ('experience', models.IntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Reyting')),
                ('specialization', models.CharField(max_length=200, verbose_name='Ixtisosligi')),
                ('bio', models.TextField(blank=True, null=True, verbose_name="Ma'lumot")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Usta',
                'verbose_name_plural': 'Ustalar',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('unit', models.CharField(default='dona', max_length=50, verbose_name='Birlik (dona, metr, etc.)')),
            ],
            options={
                'verbose_name': 'Xizmat narxi',
                'verbose_name_plural': 'Xizmat narxlari',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='Reyting (1-5)')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.master', verbose_name='Usta')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.servicerequest', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
            },
        ),
    ]
