# Generated by Django 6.0.5 on 2026-05-16 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_master_serviceprice_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255, unique=True, verbose_name='Sahifa URL (masalan: /uz/)')),
                ('title', models.CharField(max_length=255, verbose_name='Meta Title')),
                ('description', models.TextField(verbose_name='Meta Description')),
                ('keywords', models.TextField(verbose_name='Keywords (vergul bilan)')),
            ],
            options={
                'verbose_name': 'SEO Meta Teg',
                'verbose_name_plural': 'SEO Meta Teglar',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='requests/', verbose_name='Rasm (muammo tasviri)'),
        ),
        migrations.CreateModel(
            name='MasterPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ish nomi')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='main.master', verbose_name='Usta')),
            ],
            options={
                'verbose_name': 'Usta ishi',
                'verbose_name_plural': 'Ustalar ishlari',
            },
        ),
    ]
