# Generated by Django 6.0.5 on 2026-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot (EN)"),
        ),
        migrations.AddField(
            model_name='master',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot (RU)"),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ixtisosligi (EN)'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ixtisosligi (RU)'),
        ),
        migrations.AddField(
            model_name='masterportfolio',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='masterportfolio',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='masterportfolio',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish nomi (EN)'),
        ),
        migrations.AddField(
            model_name='masterportfolio',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish nomi (RU)'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_list_en',
            field=models.TextField(blank=True, null=True, verbose_name='Materiallar (EN)'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_list_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Materiallar (RU)'),
        ),
        migrations.AddField(
            model_name='material',
            name='service_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat nomi (EN)'),
        ),
        migrations.AddField(
            model_name='material',
            name='service_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat nomi (RU)'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description (EN)'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description (RU)'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords (EN)'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords (RU)'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (EN)'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (RU)'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='service_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Xizmat nomi (EN)'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='service_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Xizmat nomi (RU)'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='unit_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birlik (EN)'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='unit_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birlik (RU)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot (UZ)"),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.CharField(max_length=200, verbose_name='Ixtisosligi (UZ)'),
        ),
        migrations.AlterField(
            model_name='masterportfolio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AlterField(
            model_name='masterportfolio',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ish nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_list',
            field=models.TextField(verbose_name='Materiallar (UZ)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Xizmat nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='description',
            field=models.TextField(verbose_name='Meta Description (UZ)'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='keywords',
            field=models.TextField(verbose_name='Keywords (UZ)'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='page_url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Sahifa URL'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Meta Title (UZ)'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service_name',
            field=models.CharField(max_length=200, verbose_name='Xizmat nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='unit',
            field=models.CharField(default='dona', max_length=50, verbose_name='Birlik (UZ)'),
        ),
    ]
