# Generated by Django 6.0.5 on 2026-05-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_master_bio_en_master_bio_ru_master_specialization_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha telefon raqami"),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uy/Xonadon raqami'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mahalla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalla'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ko'cha"),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Oddiy'), ('MEDIUM', 'Muhim'), ('HIGH', 'Shoshilinch')], default='LOW', max_length=20, verbose_name='Shoshilinchlik darajasi'),
        ),
    ]
